name: deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: env to deploy to
        options:
          - stage
          - testnet
          - mainnet

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ github.event.inputs.environment }}

    env:
      ENV: ${{ github.event.inputs.environment }}

    permissions:
      contents: read
      id-token: write
      deployments: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Import secrets
        id: secrets
        uses: hashicorp/vault-action@v3.0.0
        with:
          url: https://vault.fluence.dev
          path: jwt/github
          role: ci
          method: jwt
          jwtGithubAudience: "https://github.com/fluencelabs"
          jwtTtl: 300
          secrets: |
            kv/vercel/projects/network-explorer/${{ env.ENV }} id | PROJECT_ID ;
            kv/vercel/projects/network-explorer/${{ env.ENV }} team_id | TEAM_ID ;
            kv/vercel/tokens/nahsi token | VERCEL_TOKEN ;

      - name: Deploy to vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ steps.secrets.outputs.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ vars.TEAM_ID }}
          vercel-project-id: ${{ vars.PROJECT_ID }}
          scope: ${{ env.TEAM_ID }}
