name: "release"

on:
  push:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

env:
  FORCE_COLOR: true
  CI: true

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs['release_created'] }}
      tag-name: ${{ steps.release.outputs['tag_name'] }}
      version: ${{ steps.release.outputs['version'] }}
      pr: ${{ steps.release.outputs['pr'] }}

    steps:
      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          target-branch: ${{ github.ref_name }}
          token: ${{ secrets.FLUENCEBOT_RELEASE_PLEASE_PAT }} 
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

      - name: Show output from release-please
        if: steps.release.outputs.releases_created
        env:
          RELEASE_PLEASE_OUTPUT: ${{ toJSON(steps.release.outputs) }}
        run: echo "${RELEASE_PLEASE_OUTPUT}" | jq
  
  # kras:
  #   if: needs.release-please.outputs.release-created
  #   needs: release-please
  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     ENV: kras
  #     VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID}}
  #     VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID}}
  #   secrets:
  #       VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

  # dar:
  #   if: needs.release-please.outputs.release-created
  #   needs: release-please
  #   uses: ./.github/workflows/deploy.yml
  #   with:
  #     ENV: dar
  #     VERCEL_ORG_ID: ${{ vars.VERCEL_ORG_ID}}
  #     VERCEL_PROJECT_ID: ${{ vars.VERCEL_PROJECT_ID}}
  #   secrets:
  #       VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
